# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 480)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.statusBarTest = QtGui.QGroupBox(self.centralwidget)
        self.statusBarTest.setGeometry(QtCore.QRect(10, 90, 621, 71))
        self.statusBarTest.setObjectName(_fromUtf8("statusBarTest"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.statusBarTest)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.redColor = QtGui.QRadioButton(self.statusBarTest)
        self.redColor.setObjectName(_fromUtf8("redColor"))
        self.statusBarGroup = QtGui.QButtonGroup(MainWindow)
        self.statusBarGroup.setObjectName(_fromUtf8("statusBarGroup"))
        self.statusBarGroup.addButton(self.redColor)
        self.horizontalLayout.addWidget(self.redColor)
        self.greenColor = QtGui.QRadioButton(self.statusBarTest)
        self.greenColor.setObjectName(_fromUtf8("greenColor"))
        self.statusBarGroup.addButton(self.greenColor)
        self.horizontalLayout.addWidget(self.greenColor)
        self.blueColor = QtGui.QRadioButton(self.statusBarTest)
        self.blueColor.setObjectName(_fromUtf8("blueColor"))
        self.statusBarGroup.addButton(self.blueColor)
        self.horizontalLayout.addWidget(self.blueColor)
        self.statusText = QtGui.QLineEdit(self.statusBarTest)
        self.statusText.setObjectName(_fromUtf8("statusText"))
        self.horizontalLayout.addWidget(self.statusText)
        self.showStatusBarMsg = QtGui.QPushButton(self.statusBarTest)
        self.showStatusBarMsg.setObjectName(_fromUtf8("showStatusBarMsg"))
        self.horizontalLayout.addWidget(self.showStatusBarMsg)
        self.messageBoxTest = QtGui.QGroupBox(self.centralwidget)
        self.messageBoxTest.setGeometry(QtCore.QRect(10, 10, 621, 71))
        self.messageBoxTest.setObjectName(_fromUtf8("messageBoxTest"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.messageBoxTest)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.infoMessage = QtGui.QRadioButton(self.messageBoxTest)
        self.infoMessage.setObjectName(_fromUtf8("infoMessage"))
        self.mesageBoxGroup = QtGui.QButtonGroup(MainWindow)
        self.mesageBoxGroup.setObjectName(_fromUtf8("mesageBoxGroup"))
        self.mesageBoxGroup.addButton(self.infoMessage)
        self.horizontalLayout_3.addWidget(self.infoMessage)
        self.warningMessage = QtGui.QRadioButton(self.messageBoxTest)
        self.warningMessage.setObjectName(_fromUtf8("warningMessage"))
        self.mesageBoxGroup.addButton(self.warningMessage)
        self.horizontalLayout_3.addWidget(self.warningMessage)
        self.errorMessage = QtGui.QRadioButton(self.messageBoxTest)
        self.errorMessage.setObjectName(_fromUtf8("errorMessage"))
        self.mesageBoxGroup.addButton(self.errorMessage)
        self.horizontalLayout_3.addWidget(self.errorMessage)
        self.questionMessage = QtGui.QRadioButton(self.messageBoxTest)
        self.questionMessage.setObjectName(_fromUtf8("questionMessage"))
        self.mesageBoxGroup.addButton(self.questionMessage)
        self.horizontalLayout_3.addWidget(self.questionMessage)
        self.messageText = QtGui.QLineEdit(self.messageBoxTest)
        self.messageText.setObjectName(_fromUtf8("messageText"))
        self.horizontalLayout_3.addWidget(self.messageText)
        self.showMessageBox = QtGui.QPushButton(self.messageBoxTest)
        self.showMessageBox.setObjectName(_fromUtf8("showMessageBox"))
        self.horizontalLayout_3.addWidget(self.showMessageBox)
        self.pythonTimerTest = QtGui.QGroupBox(self.centralwidget)
        self.pythonTimerTest.setGeometry(QtCore.QRect(10, 180, 621, 71))
        self.pythonTimerTest.setObjectName(_fromUtf8("pythonTimerTest"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.pythonTimerTest)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.timerInterval = QtGui.QSpinBox(self.pythonTimerTest)
        self.timerInterval.setMinimum(5)
        self.timerInterval.setMaximum(60)
        self.timerInterval.setSingleStep(5)
        self.timerInterval.setProperty("value", 5)
        self.timerInterval.setObjectName(_fromUtf8("timerInterval"))
        self.horizontalLayout_7.addWidget(self.timerInterval)
        self.stopTimer = QtGui.QPushButton(self.pythonTimerTest)
        self.stopTimer.setObjectName(_fromUtf8("stopTimer"))
        self.horizontalLayout_7.addWidget(self.stopTimer)
        self.timerText = QtGui.QLineEdit(self.pythonTimerTest)
        self.timerText.setObjectName(_fromUtf8("timerText"))
        self.horizontalLayout_7.addWidget(self.timerText)
        self.showTimerMsg = QtGui.QPushButton(self.pythonTimerTest)
        self.showTimerMsg.setObjectName(_fromUtf8("showTimerMsg"))
        self.horizontalLayout_7.addWidget(self.showTimerMsg)
        self.windowsTitleTest = QtGui.QGroupBox(self.centralwidget)
        self.windowsTitleTest.setGeometry(QtCore.QRect(10, 360, 621, 71))
        self.windowsTitleTest.setObjectName(_fromUtf8("windowsTitleTest"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.windowsTitleTest)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.titleText = QtGui.QLineEdit(self.windowsTitleTest)
        self.titleText.setObjectName(_fromUtf8("titleText"))
        self.horizontalLayout_6.addWidget(self.titleText)
        self.showTitleMsg = QtGui.QPushButton(self.windowsTitleTest)
        self.showTitleMsg.setObjectName(_fromUtf8("showTitleMsg"))
        self.horizontalLayout_6.addWidget(self.showTitleMsg)
        self.pythonThreadingTest = QtGui.QGroupBox(self.centralwidget)
        self.pythonThreadingTest.setGeometry(QtCore.QRect(10, 270, 621, 71))
        self.pythonThreadingTest.setObjectName(_fromUtf8("pythonThreadingTest"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.pythonThreadingTest)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.threadingText = QtGui.QLineEdit(self.pythonThreadingTest)
        self.threadingText.setObjectName(_fromUtf8("threadingText"))
        self.horizontalLayout_8.addWidget(self.threadingText)
        self.showThreadingMsg = QtGui.QPushButton(self.pythonThreadingTest)
        self.showThreadingMsg.setObjectName(_fromUtf8("showThreadingMsg"))
        self.horizontalLayout_8.addWidget(self.showThreadingMsg)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionClose)
        self.menu.addSeparator()
        self.menu.addAction(self.action_2)
        self.menu_2.addAction(self.actionAbout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyQt4 Application Framework Demo", None))
        self.statusBarTest.setTitle(_translate("MainWindow", "状态栏消息", None))
        self.redColor.setText(_translate("MainWindow", "红色", None))
        self.greenColor.setText(_translate("MainWindow", "绿色", None))
        self.blueColor.setText(_translate("MainWindow", "蓝色", None))
        self.showStatusBarMsg.setToolTip(_translate("MainWindow", "在窗口状态栏上显示一条消息", None))
        self.showStatusBarMsg.setText(_translate("MainWindow", "显示消息", None))
        self.messageBoxTest.setTitle(_translate("MainWindow", "对话框消息", None))
        self.infoMessage.setText(_translate("MainWindow", "信息", None))
        self.warningMessage.setText(_translate("MainWindow", "警告", None))
        self.errorMessage.setText(_translate("MainWindow", "错误", None))
        self.questionMessage.setText(_translate("MainWindow", "确认", None))
        self.showMessageBox.setText(_translate("MainWindow", "显示消息", None))
        self.pythonTimerTest.setTitle(_translate("MainWindow", "Python 定时器消息", None))
        self.stopTimer.setText(_translate("MainWindow", "停止定时器", None))
        self.showTimerMsg.setToolTip(_translate("MainWindow", "在窗口状态栏上显示一条消息", None))
        self.showTimerMsg.setText(_translate("MainWindow", "显示消息", None))
        self.windowsTitleTest.setTitle(_translate("MainWindow", "窗口标题栏消息", None))
        self.showTitleMsg.setToolTip(_translate("MainWindow", "在窗口状态栏上显示一条消息", None))
        self.showTitleMsg.setText(_translate("MainWindow", "显示消息", None))
        self.pythonThreadingTest.setTitle(_translate("MainWindow", "Python 线程消息", None))
        self.showThreadingMsg.setToolTip(_translate("MainWindow", "在窗口状态栏上显示一条消息", None))
        self.showThreadingMsg.setText(_translate("MainWindow", "显示消息", None))
        self.menu.setTitle(_translate("MainWindow", "文件", None))
        self.menu_2.setTitle(_translate("MainWindow", "关于", None))
        self.actionOpen.setText(_translate("MainWindow", "打开", None))
        self.actionOpen.setStatusTip(_translate("MainWindow", "打开文件", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionClose.setText(_translate("MainWindow", "保存", None))
        self.actionClose.setStatusTip(_translate("MainWindow", "保存文件", None))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionAbout.setText(_translate("MainWindow", "关于", None))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1", None))
        self.action_2.setText(_translate("MainWindow", "退出", None))
        self.action_2.setShortcut(_translate("MainWindow", "Ctrl+Q", None))

